# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7ae6c16028ec687a68a60a03f2763ffc18e8e1e5a653c3ae8126f619b70a58e613e24e8c5be7d2e616c0ec66137e59355e4c220212949f29d134c7814c1e72c

test:
  secret_key_base: b86cf0890862ddae6e53bb8d6607e0a24a1cb603b6adfa209d2fed457bba401ece00a3fc2952fedbbe6c9f3246f84a29c6e1e4fb722d51ded18867cdb006077c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
